---
id: sesha
name: Sesha
full: Inventory application
description: >
  Sesha allows you to define categories with a rich set of attributes to manage
  your inventory stock
list: horde
type: application
